// Deliverable 1.13 — §34's admission rule, made executable.
//
// Records the exact set of frontmatter keys and task attributes the system reads,
// and fails when it grows. Its first job is not policing a rich view that does not
// exist: it is catching Phase 1 and Phase 2 code quietly widening the schema, which
// is the same failure and far likelier to happen first.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { readdir } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(process.cwd());
const PIN = join(root, "schema.json");

async function sources(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "dist") continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await sources(full)));
    else if (/\.ts$/.test(entry.name) && !/\.test\.ts$/.test(entry.name)) out.push(full);
  }
  return out;
}

const files = await sources(join(root, "packages"));
const taskAttributes = new Set();
const frontmatterKeys = new Set();

for (const file of files) {
  const text = readFileSync(file, "utf8");
  // `[name: value]` on a task line, quoted or not, however it is written or matched.
  // TypeScript index signatures — `[key: string]: unknown` — look identical and are
  // not attributes, so they are excluded by their trailing `]:` rather than by name.
  for (const m of text.matchAll(/\[([a-z][a-z0-9-]*):\s*(?:"|\$\{|[a-z])/g)) {
    const tail = text.slice(m.index, m.index + 40);
    if (/^\[[a-z][a-z0-9-]*:\s*(string|number|boolean|symbol)\]\s*:/.test(tail)) continue;
    taskAttributes.add(m[1]);
  }
  for (const m of text.matchAll(/\\\[([a-z][a-z0-9-]*):/g)) taskAttributes.add(m[1]);
  // Frontmatter keys the code reads or writes by name.
  for (const m of text.matchAll(/\b(?:patchFrontmatter|frontmatter)\w*\([^)]*?["'](\w+)["']/g)) {
    frontmatterKeys.add(m[1]);
  }
  for (const m of text.matchAll(/\bo(?:bject)?\.(status|tags|aliases|week|frozen)\b/g)) {
    frontmatterKeys.add(m[1]);
  }
}

// Read explicitly rather than inferred: these are named in code as object fields.
for (const key of ["status", "tags", "aliases", "week", "frozen"]) frontmatterKeys.add(key);
for (const attr of ["deadline", "scheduled", "completed", "reminder", "event"]) {
  taskAttributes.add(attr);
}

const current = {
  $comment:
    "GENERATED by scripts/pin-schema.mjs. If this grew, a feature added a field to " +
    "everyone's Markdown. That is a design conversation (see §34), not a merge.",
  taskAttributes: [...taskAttributes].sort(),
  frontmatterKeys: [...frontmatterKeys].sort(),
};

if (process.argv.includes("--write") || !existsSync(PIN)) {
  // Reasons survive a re-pin. Why a field was admitted is the only durable part of
  // this file — regenerating it and silently dropping that would leave a list of
  // fields nobody can defend.
  const existing = existsSync(PIN) ? JSON.parse(readFileSync(PIN, "utf8")) : {};
  if (existing.$why) current.$why = existing.$why;
  writeFileSync(PIN, JSON.stringify(current, null, 2) + "\n");
  console.log(`schema pinned: ${current.taskAttributes.length} task attributes, ` +
              `${current.frontmatterKeys.length} frontmatter keys`);
  process.exit(0);
}

const pinned = JSON.parse(readFileSync(PIN, "utf8"));
const grew = (name, before, after) => {
  const added = after.filter((k) => !before.includes(k));
  const removed = before.filter((k) => !after.includes(k));
  if (added.length) console.error(`  ${name} ADDED:   ${added.join(", ")}`);
  if (removed.length) console.error(`  ${name} removed: ${removed.join(", ")}`);
  return added.length > 0;
};

const a = grew("task attribute", pinned.taskAttributes, current.taskAttributes);
const b = grew("frontmatter key", pinned.frontmatterKeys, current.frontmatterKeys);
if (a || b) {
  console.error(
    "\nThe metadata tax went up. §34: if someone never uses the feature that needed this,\n" +
    "does their Markdown still need the field? If yes, it does not belong in core.\n" +
    "Deliberate? Re-run with --write and say why in the commit.",
  );
  process.exit(1);
}
console.log(`schema unchanged: ${current.taskAttributes.length} task attributes, ` +
            `${current.frontmatterKeys.length} frontmatter keys`);
